server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://enrollment-postgres:5432/edubase_enrollment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:29092
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  issuer: ${JWT_ISSUER:edubase-auth}
  audience: ${JWT_AUDIENCE:api-gateway}

services:
  api-gateway:
    url: http://api-gateway:8090
  user-service:
    url: http://user-service:8081
  course-service:
    url: http://course-service:8083

app:
  internal:
    api-key: ${INTERNAL_API_KEY}

grpc:
  client:
    user:
      host: user-service
      port: 9091
    course:
      host: course-service
      port: 9092
    payment:
      host: payment-service
      port: 9095
