services:

  # AUTH DB
  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  # USER DB
  user-postgres:
    image: postgres:15
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_DB: edubase_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  # REDIS
  redis:
    image: redis:7
    container_name: edubase-redis
    restart: always
    ports:
      - "6379:6379"

  # COURSE DB
  course-mongo:
    image: mongo:7
    container_name: course-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: edubase_course_db
    ports:
      - "27017:27017"
    volumes:
      - course_mongo_data:/data/db


volumes:
  auth_postgres_data:
  user_postgres_data:
  course_mongo_data:
