server:
  port: ${COURSE_SERVICE_PORT:8083}

spring:
  application:
    name: course-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  secret: ${JWT_SECRET}

course:
  media:
    base-path: ${COURSE_MEDIA_BASE_PATH:videos}
  sample:
    enabled: ${COURSE_SAMPLE_ENABLED:true}
