spring:
  config:
    activate:
      on-profile: dev
  cache:
    type: ${CACHE_TYPE:simple}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/edubase_course_db}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

auth:
  debug: ${AUTH_DEBUG:false}

app:
  gateway-url: ${GATEWAY_URL:http://localhost:8090}

management:
  endpoints:
    web:
      exposure:
        include: health,info
