server:
  port: ${COURSE_SERVICE_PORT:8083}

spring:
  application:
    name: course-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cache:
    type: ${CACHE_TYPE:simple}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/edubase_course_db}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}

auth:
  debug: ${AUTH_DEBUG:false}

app:
  gateway-url: ${GATEWAY_URL:http://localhost:8090}

management:
  endpoints:
    web:
      exposure:
        include: health,info
