apiVersion: v1
kind: Secret
metadata:
  name: edubase-secrets
  namespace: edubase
type: Opaque
stringData:
  JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  INTERNAL_API_KEY: course-service-aaPiKKee-y

  AUTH_DB_PASSWORD: postgres
  USER_DB_PASSWORD: postgres
  COURSE_DB_PASSWORD: postgres
  ENROLLMENT_DB_PASSWORD: postgres
  PAYMENT_DB_PASSWORD: postgres
  REVIEW_DB_PASSWORD: postgres
  POSTGRES_PASSWORD: postgres

  MINIO_ROOT_USER: eeeDuBasseeEMiiiiIIniOO00UserNnnAmeffor
  MINIO_ROOT_PASSWORD: eDuubasssEemiIIniOoAAAaaAddmMinkey
  USER_MEDIA_MINIO_ACCESS_KEY: eeeDuBasseeEMiiiiIIniOO00UserNnnAmeffor
  USER_MEDIA_MINIO_SECRET_KEY: eDuubasssEemiIIniOoAAAaaAddmMinkey
  COURSE_MEDIA_MINIO_ACCESS_KEY: eeeDuBasseeEMiiiiIIniOO00UserNnnAmeffor
  COURSE_MEDIA_MINIO_SECRET_KEY: eDuubasssEemiIIniOoAAAaaAddmMinkey

  GMAIL_USERNAME: EduBaseSup@gmail.com
  GMAIL_APP_PASSWORD: "qdqa hxxg ndwf eibm"

  PAYMENT_GATEWAY_WEBHOOK_SECRET: change-me-payment-webhook-secret
