apiVersion: v1
kind: Secret
metadata:
  name: edubase-secrets
  namespace: edubase
type: Opaque
stringData:
  JWT_SECRET: CHANGE_ME_WITH_LONG_RANDOM_JWT_SECRET
  INTERNAL_API_KEY: CHANGE_ME_WITH_LONG_RANDOM_INTERNAL_API_KEY

  AUTH_DB_PASSWORD: CHANGE_ME_AUTH_DB_PASSWORD
  USER_DB_PASSWORD: CHANGE_ME_USER_DB_PASSWORD
  COURSE_DB_PASSWORD: CHANGE_ME_COURSE_DB_PASSWORD
  ENROLLMENT_DB_PASSWORD: CHANGE_ME_ENROLLMENT_DB_PASSWORD
  PAYMENT_DB_PASSWORD: CHANGE_ME_PAYMENT_DB_PASSWORD
  REVIEW_DB_PASSWORD: CHANGE_ME_REVIEW_DB_PASSWORD
  POSTGRES_PASSWORD: CHANGE_ME_POSTGRES_PASSWORD

  MINIO_ROOT_USER: CHANGE_ME_MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD: CHANGE_ME_MINIO_ROOT_PASSWORD
  USER_MEDIA_MINIO_ACCESS_KEY: CHANGE_ME_USER_MEDIA_MINIO_ACCESS_KEY
  USER_MEDIA_MINIO_SECRET_KEY: CHANGE_ME_USER_MEDIA_MINIO_SECRET_KEY
  COURSE_MEDIA_MINIO_ACCESS_KEY: CHANGE_ME_COURSE_MEDIA_MINIO_ACCESS_KEY
  COURSE_MEDIA_MINIO_SECRET_KEY: CHANGE_ME_COURSE_MEDIA_MINIO_SECRET_KEY

  GMAIL_USERNAME: CHANGE_ME_GMAIL_USERNAME
  GMAIL_APP_PASSWORD: CHANGE_ME_GMAIL_APP_PASSWORD

  PAYMENT_GATEWAY_WEBHOOK_SECRET: CHANGE_ME_PAYMENT_GATEWAY_WEBHOOK_SECRET
