server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://review-postgres:5432/edubase_review_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  issuer: ${JWT_ISSUER:edubase-auth}
  audience: ${JWT_AUDIENCE:api-gateway}

services:
  api-gateway:
    url: http://api-gateway:8090
  course-service:
    url: http://course-service:8083
